# Generated by Django 5.2.1 on 2025-06-04 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='gray', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('concluida', models.BooleanField(default=False)),
                ('agendada_para', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('alta', '🔥 Alta'), ('media', '🟡 Média'), ('baixa', '🟢 Baixa')], default='media', max_length=10)),
                ('mudancas_data', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tarefas.categoria')),
            ],
        ),
    ]
